version: '3'

services:

  api-server:
    container_name: api-server
    build: api-server
    restart: always
    ports:
      - 1234:1234
    volumes:
      - /root/db:/var/lib/packetproxyhub
      - ./api-server/etc_packetproxyhub:/etc/packetproxyhub

  web-client:
    container_name: web-client
    build: web-client
    restart: always
    ports:
      - 443:443
    volumes:
      - ./web-client/etc_nginx_certs:/etc/nginx/certs

