# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snap_meta.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("snap_meta.proto", :syntax => :proto2) do
    add_message "emulator_snapshot.Image" do
      optional :type, :enum, 1, "emulator_snapshot.Image.Type"
      optional :path, :string, 2
      optional :present, :bool, 3
      optional :size, :int64, 4
      optional :modification_time, :int64, 5
    end
    add_enum "emulator_snapshot.Image.Type" do
      value :IMAGE_TYPE_UNKNOWN, 0
      value :IMAGE_TYPE_KERNEL, 1
      value :IMAGE_TYPE_KERNEL_RANCHU, 2
      value :IMAGE_TYPE_SYSTEM, 3
      value :IMAGE_TYPE_SYSTEM_COPY, 4
      value :IMAGE_TYPE_DATA, 5
      value :IMAGE_TYPE_DATA_COPY, 6
      value :IMAGE_TYPE_RAMDISK, 7
      value :IMAGE_TYPE_SDCARD, 8
      value :IMAGE_TYPE_CACHE, 9
      value :IMAGE_TYPE_VENDOR, 10
      value :IMAGE_TYPE_ENCRYPTION_KEY, 11
    end
    add_message "emulator_snapshot.Host" do
      optional :gpu_driver, :string, 4
      optional :hypervisor, :int32, 5
    end
    add_message "emulator_snapshot.Config" do
      repeated :enabled_features, :int32, 1
      optional :selected_renderer, :int32, 2
      optional :cpu_core_count, :int32, 3
      optional :ram_size_bytes, :int64, 4
    end
    add_message "emulator_snapshot.SaveStats" do
      optional :incremental, :uint32, 1
      optional :duration, :uint64, 2
      optional :ram_changed_bytes, :uint64, 3
    end
    add_message "emulator_snapshot.Snapshot" do
      optional :version, :int32, 1
      optional :creation_time, :int64, 2
      repeated :images, :message, 3, "emulator_snapshot.Image"
      optional :host, :message, 4, "emulator_snapshot.Host"
      optional :config, :message, 5, "emulator_snapshot.Config"
      optional :failed_to_load_reason_code, :int64, 7
      optional :guest_data_partition_mounted, :bool, 8
      optional :rotation, :int32, 9
      optional :invalid_loads, :int32, 10
      optional :successful_loads, :int32, 11
      optional :logical_name, :string, 12
      optional :parent, :string, 13
      optional :description, :string, 14
      repeated :save_stats, :message, 15, "emulator_snapshot.SaveStats"
      optional :folded, :bool, 16
      repeated :launch_parameters, :string, 17
      optional :emulator_build_id, :string, 18
      optional :system_image_build_id, :string, 19
    end
  end
end

module EmulatorSnapshot
  Image = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("emulator_snapshot.Image").msgclass
  Image::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("emulator_snapshot.Image.Type").enummodule
  Host = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("emulator_snapshot.Host").msgclass
  Config = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("emulator_snapshot.Config").msgclass
  SaveStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("emulator_snapshot.SaveStats").msgclass
  Snapshot = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("emulator_snapshot.Snapshot").msgclass
end
